---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-config
  namespace: wp
data:
  # Adding new entries here will make them appear as files in the deployment.
  # Please update k8s.io/k8s.io/README.md when you update this file
  default.conf: |
    server {
        listen 80;

        location /pup {
          return 200 'UP';
          add_header Content-Type text/plain;
        }

        location / {
          rewrite ^(.*) https://wp.papezt.com$request_uri? permanent;
        }
    }

    server {
        listen 443 ssl http2;
        server_tokens off;
        merge_slashes off;

        #SSL CONFIGURATION
        ssl_certificate      /etc/nginx/cert/tls.crt;
        ssl_certificate_key  /etc/nginx/cert/tls.key;
        ssl_prefer_server_ciphers on;
        ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers         EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128 \
                            -GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384: \
                            ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256: \
                            DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA: \
                            EDH-RSA-DES-CBC3-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256: \
                            AES256-SHA:AES128-SHA:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4;

        location /  {
          proxy_pass  http://wp.wp.svc.cluster.local:80;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP  $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto https;
        }
    }
