---
apiVersion: v1
kind: Service
metadata:
  namespace: wp
  name: nginx-proxy
  labels:
    name: nginx-proxy
    tier: proxy
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  selector:
    app: nginx-proxy
  type: LoadBalancer
  loadBalancerIP: "35.187.187.165"
