---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp
  namespace: wp
  labels:
    app: wp
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: wp
      tier: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: wp
        tier: frontend
    spec:
      containers:
        - image: wordpress:5.0.3-php7.3-apache
          name: wp
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 20
            timeoutSeconds: 5
          env:
            - name: WORDPRESS_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: wp-secret
                  key: DB_CONN
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: wp-secret
                  key: DB_USER
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wp-secret
                  key: DB_PASS
          ports:
            - containerPort: 80
              name: wp
          volumeMounts:
            - name: wp
              mountPath: /var/www/html
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
      volumes:
        - name: wp
          persistentVolumeClaim:
            claimName: wp
